In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import gridspec
import matplotlib.lines as mlines
from matplotlib.font_manager import FontProperties
import seaborn as sns
from scipy.stats import norm, pearsonr, spearmanr
import scipy.stats as stats
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all' #last_expr

sns.set_context("paper")
simHei = FontProperties(fname=r'/usr/share/fonts/Chinses/simhei.ttf', size=10)

In [2]:
meta = pd.read_csv('../data/Preprocess/rawdata_metadata.tsv', sep='\t', index_col=0)
meta.head()

,experiment_id／name,Age,出生体重(kg),出生身高(cm),目前体重(kg),目前身高(cm),长期居住地(城镇：0， 农村：1),患儿主要带养人(父母：0，（外）祖父母:1),"饲养宠物(否 :0,是：1)",母亲生育年龄（岁),...,Dodecanedioic-2,N-Acetyltyrosine-3,Uric-4,"3,6-Epoxydodecanedioic-2",3-OH-dodecanedioic-3,"3,6-Epoxytetradecanedioic-2",Unnamed: 362,Unnamed: 43,体重kg.1,身高cm.1
N579,exp_01,6.333,5.6,58.0,20.0,119.0,0,0,0.0,28.0,...,0.00,0.00,2.63,9.52,2.10,2.42,NaN,NaN,NaN,NaN
PP196_1,exp_01,6.250,NaN,NaN,23.7,116.8,1,0,0.0,24.0,...,0.22,0.51,0.00,4.38,0.34,0.20,100.0,NaN,NaN,NaN
PP99_1,NaN,6.920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,超前,NaN,NaN
PP02_1,NaN,1.830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PP65_1,NaN,4.670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
microbiome = pd.read_csv('../data/Preprocess/rawdata_16S_abundance.tsv', sep='\t', index_col=0)
microbiome.head()

,N579,PP196_1,PP01_1,N621,N399,PP117_1,PP80_1,N556,PP144_1,PP190_1,...,N607,PP106_1,N569,PP37_1,N568,N630,N540,PP41_1,N401,PP119_1
#OTU ID,,,,,,,,,,,,,,,,,,,,,
44001a72292c6ac78f98d2ffaac23065,2.767849,3.595795,15.481491,17.990444,4.483103,9.982057,6.053326,2.459807,13.499211,2.756187,...,12.580336,6.756263,2.159016,22.850765,40.771558,3.832416,3.476722,7.667644,6.834232,3.646867
3016b070726d0a9e6cdb87c4a3914d07,1.514439,1.535658,1.322523,0.392401,1.487702,4.264077,0.701903,6.513934,2.441378,0.791569,...,0.571277,0.579189,0.437207,0.386204,0.546048,19.311710,0.361725,3.666054,0.772952,1.642549
6af5f8ea781a98464482a500ff544d17,0.681968,0.891171,1.465408,0.533204,0.755849,5.427727,5.935557,0.734191,0.923923,0.193124,...,1.240487,0.447044,0.555105,0.439781,1.950170,3.740709,0.489239,0.989213,1.990769,1.207842
c3367f41d47ad8e82a9303dd36c7feb3,1.041765,0.408916,2.678275,7.393301,0.455909,2.155787,1.446203,0.225080,2.707444,0.858328,...,26.101238,0.497652,0.346327,0.174127,8.552383,0.917077,0.621959,0.236119,0.519935,0.338429
7d922b6af519ebac697c9b4025768967,0.091713,10.014001,0.638001,0.092330,2.283543,0.350942,0.508762,0.699357,2.096369,0.147823,...,0.055087,0.388000,0.341414,0.154035,0.354576,0.328217,0.307076,0.320624,0.353111,0.218812

In [5]:
metabolism = pd.read_csv('../data/Preprocess/rawdata_metabolism_abundance.tsv', sep='\t', index_col=0)
metabolism.head()

,PP99_1,N579,PP02_1,PP65_1,PP01_1,PP09_1,N621,PP117_1,PP80_1,N556,...,N628,PP140_1,N564,N607,PP37_1,N569,N568,PP125_1,N540,PP41_1
pos_metabolite_ID,,,,,,,,,,,,,,,,,,,,,
POS_7,0.002677,0.003906,0.033713,0.003538,0.003946,0.005640,0.018363,0.007910,0.009438,0.014900,...,0.000592,0.001799,0.000235,0.006882,0.000397,0.003298,0.003726,0.046869,0.001400,0.001445
POS_8,0.010665,0.038386,0.079751,0.015239,0.006436,0.017229,0.050683,0.003340,0.005866,0.004384,...,0.044877,0.003442,0.020886,0.041815,0.004280,0.016329,0.042281,0.038650,0.036096,0.004707
POS_10,0.067654,0.000701,0.000889,0.076852,0.071915,0.000511,0.000658,0.263614,0.002931,0.001440,...,0.000799,0.052581,0.000566,0.000609,0.020760,0.000765,0.000590,0.000604,0.001438,0.058367
POS_24,0.014283,0.019426,0.013160,0.013827,0.053086,0.012890,0.017034,0.024071,0.010854,0.017674,...,0.011142,0.016451,0.014555,0.011066,0.009294,0.019891,0.019811,0.018014,0.009332,0.010964
POS_26,0.025595,0.013861,0.018086,0.008634,0.017666,0.015677,0.025903,0.016628,0.011860,0.017793,...,0.015193,0.016763,0.032790,0.029224,0.019837,0.036657,0.024904,0.040068,0.031997,0.011772

In [6]:
microbiome.shape, metabolism.shape

((124, 168), (1522, 129))

In [9]:
overlap = set(microbiome.columns)&set(metabolism.columns)
overlap_normal = [i for i in overlap if 'N' in i]
overlap_PP = [i for i in overlap if 'PP' in i]
len(overlap), len(overlap_normal), len(overlap_PP)

(97, 41, 56)

In [11]:
age_n = meta.loc[overlap_normal, 'Age']
age_n.mean(), 1.96 * age_n.std() / np.sqrt(len(age_n)) #95置信区间

(6.211292195121951, 0.6291203628578798)

In [12]:
age_pp = meta.loc[overlap_PP, 'Age']
age_pp.mean(), 1.96 * age_pp.std() / np.sqrt(len(age_pp)) #95置信区间

(6.88980625, 0.5298802245975738)

In [13]:
from scipy import stats
stats.ttest_ind(age_n,age_pp)

Ttest_indResult(statistic=-1.6208058172573365, pvalue=0.10837397749040993)